import type { GlobalTypography, WorksheetPageStyle, SectionStyle } from "../../store";

export type AIPreset = {
  id: string;
  label: string;
  emoji: string;
  desc: string;
  typography: Partial<GlobalTypography>;
  pageStyle: Partial<WorksheetPageStyle>;
  sectionDefaults: Partial<Pick<SectionStyle, "bgColor" | "borderStyle" | "borderColor" | "borderWidth" | "rounded">>;
};

export const AI_STYLE_PRESETS: AIPreset[] = [
  {
    id: "fun-elementary",
    label: "Fun Elementary",
    emoji: "🌈",
    desc: "Colorful and energetic for younger students",
    typography: {
      titleFont: "Fredoka",
      titleHeadingStyle: "bubble",
      headingFont: "Nunito",
      bodyFont: "Nunito",
      questionFont: "Nunito",
      vocabFont: "Nunito",
      titleColor: "#7c3aed",
      headingColor: "#2563eb",
      accentColor: "#7c3aed",
      lineHeight: 1.8,
    },
    pageStyle: { bgColor: "#fffdf7", titleFont: "Fredoka", bodyFont: "Nunito" },
    sectionDefaults: { bgColor: "#f5f3ff", borderStyle: "none", rounded: true },
  },
  {
    id: "cute-classroom",
    label: "Cute Classroom",
    emoji: "🍎",
    desc: "Friendly and warm with soft pastel tones",
    typography: {
      titleFont: "Baloo 2",
      titleHeadingStyle: "pastel-label",
      headingFont: "Quicksand",
      bodyFont: "Quicksand",
      questionFont: "Quicksand",
      vocabFont: "Nunito",
      titleColor: "#be185d",
      headingColor: "#0891b2",
      accentColor: "#ec4899",
      lineHeight: 1.7,
    },
    pageStyle: { bgColor: "#fff8f0", titleFont: "Baloo 2", bodyFont: "Quicksand" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "dashed", borderColor: "#f9a8d4", borderWidth: 2, rounded: true },
  },
  {
    id: "clean-modern",
    label: "Clean Modern",
    emoji: "⬜",
    desc: "Minimal and professional, any grade level",
    typography: {
      titleFont: "Outfit",
      titleHeadingStyle: "underline-accent",
      headingFont: "Inter",
      bodyFont: "Inter",
      questionFont: "Inter",
      vocabFont: "Inter",
      titleColor: "#0f172a",
      headingColor: "#1e293b",
      accentColor: "#7c3aed",
      lineHeight: 1.6,
    },
    pageStyle: { bgColor: "#ffffff", titleFont: "Outfit", bodyFont: "Inter" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "solid", borderColor: "#e2e8f0", borderWidth: 1, rounded: false },
  },
  {
    id: "elegant-soft",
    label: "Elegant & Soft",
    emoji: "🌸",
    desc: "Refined cursive headings with soft lavender",
    typography: {
      titleFont: "Great Vibes",
      titleHeadingStyle: "cursive",
      headingFont: "Nunito",
      bodyFont: "DM Sans",
      questionFont: "DM Sans",
      vocabFont: "Nunito",
      titleColor: "#7c3aed",
      headingColor: "#6d28d9",
      accentColor: "#a78bfa",
      lineHeight: 1.7,
    },
    pageStyle: { bgColor: "#faf5ff", titleFont: "Great Vibes", bodyFont: "DM Sans" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "none", rounded: false },
  },
  {
    id: "notebook-style",
    label: "Notebook Style",
    emoji: "📓",
    desc: "Handwritten feel with notebook paper warmth",
    typography: {
      titleFont: "Caveat",
      titleHeadingStyle: "notebook-tab",
      headingFont: "Patrick Hand",
      bodyFont: "Patrick Hand",
      questionFont: "Patrick Hand",
      vocabFont: "Caveat",
      titleColor: "#1e3a5f",
      headingColor: "#1e40af",
      accentColor: "#2563eb",
      lineHeight: 1.9,
    },
    pageStyle: { bgColor: "#fffef0", titleFont: "Caveat", bodyFont: "Patrick Hand" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "dashed", borderColor: "#93c5fd", borderWidth: 1, rounded: false },
  },
  {
    id: "pastel-classroom",
    label: "Pastel Classroom",
    emoji: "🎨",
    desc: "Gentle pastels, perfect for any subject area",
    typography: {
      titleFont: "Nunito",
      titleHeadingStyle: "pastel-label",
      headingFont: "Quicksand",
      bodyFont: "Nunito",
      questionFont: "Quicksand",
      vocabFont: "Nunito",
      titleColor: "#6d28d9",
      headingColor: "#0891b2",
      accentColor: "#7c3aed",
      lineHeight: 1.7,
    },
    pageStyle: { bgColor: "#f0fdfa", titleFont: "Nunito", bodyFont: "Nunito" },
    sectionDefaults: { bgColor: "#f5f3ff", borderStyle: "none", rounded: true },
  },
  {
    id: "bold-handout",
    label: "Bold Handout",
    emoji: "📋",
    desc: "Clear and strong — easy to read at a glance",
    typography: {
      titleFont: "Poppins",
      titleHeadingStyle: "banner",
      headingFont: "Poppins",
      bodyFont: "Open Sans",
      questionFont: "Open Sans",
      vocabFont: "Open Sans",
      titleColor: "#1a1a2e",
      headingColor: "#1a1a2e",
      accentColor: "#1d4ed8",
      lineHeight: 1.6,
    },
    pageStyle: { bgColor: "#ffffff", titleFont: "Poppins", bodyFont: "Open Sans" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "solid", borderColor: "#1d4ed8", borderWidth: 2, rounded: false },
  },
  {
    id: "cursive-headings",
    label: "Cursive Headings",
    emoji: "🖋️",
    desc: "Elegant cursive titles, teachers love this one",
    typography: {
      titleFont: "Sacramento",
      titleHeadingStyle: "cursive",
      headingFont: "Sacramento",
      bodyFont: "Nunito",
      questionFont: "DM Sans",
      vocabFont: "Nunito",
      titleColor: "#7c3aed",
      headingColor: "#a21caf",
      accentColor: "#c026d3",
      lineHeight: 1.7,
    },
    pageStyle: { bgColor: "#fdf4ff", titleFont: "Sacramento", bodyFont: "Nunito" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "none", rounded: false },
  },
  {
    id: "playful-lower-grade",
    label: "Playful Lower Grade",
    emoji: "⭐",
    desc: "Big, bold, cheerful — great for K-2",
    typography: {
      titleFont: "Gloria Hallelujah",
      titleHeadingStyle: "shadow",
      headingFont: "Fredoka",
      bodyFont: "Nunito",
      questionFont: "Nunito",
      vocabFont: "Fredoka",
      titleColor: "#b45309",
      headingColor: "#15803d",
      accentColor: "#f59e0b",
      lineHeight: 2.0,
    },
    pageStyle: { bgColor: "#fefce8", titleFont: "Gloria Hallelujah", bodyFont: "Nunito" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "dotted", borderColor: "#fcd34d", borderWidth: 2, rounded: true },
  },
  {
    id: "primary-grade",
    label: "Primary Grade",
    emoji: "🔤",
    desc: "Large friendly text for beginning readers",
    typography: {
      titleFont: "Fredoka",
      titleHeadingStyle: "bubble",
      headingFont: "Baloo 2",
      bodyFont: "Nunito",
      questionFont: "Nunito",
      vocabFont: "Baloo 2",
      titleColor: "#dc2626",
      headingColor: "#1d4ed8",
      accentColor: "#dc2626",
      lineHeight: 2.0,
      baseSize: 1.1,
    },
    pageStyle: { bgColor: "#ffffff", titleFont: "Fredoka", bodyFont: "Nunito" },
    sectionDefaults: { bgColor: "#eff6ff", borderStyle: "solid", borderColor: "#bfdbfe", borderWidth: 2, rounded: true },
  },
  {
    id: "minimalist",
    label: "Minimalist",
    emoji: "🤍",
    desc: "Ultra clean — nothing distracts from content",
    typography: {
      titleFont: "Inter",
      titleHeadingStyle: "plain",
      headingFont: "Inter",
      bodyFont: "Inter",
      questionFont: "Inter",
      vocabFont: "Inter",
      titleColor: "#111827",
      headingColor: "#374151",
      accentColor: "#6b7280",
      lineHeight: 1.6,
      letterSpacing: 0,
    },
    pageStyle: { bgColor: "#ffffff", titleFont: "Inter", bodyFont: "Inter" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "none", rounded: false },
  },
  {
    id: "upper-elementary",
    label: "Upper Elementary",
    emoji: "🎓",
    desc: "Academic but friendly for grades 3-6",
    typography: {
      titleFont: "Outfit",
      titleHeadingStyle: "underline-accent",
      headingFont: "Poppins",
      bodyFont: "Open Sans",
      questionFont: "Open Sans",
      vocabFont: "Poppins",
      titleColor: "#1e3a5f",
      headingColor: "#1e40af",
      accentColor: "#2563eb",
      lineHeight: 1.65,
    },
    pageStyle: { bgColor: "#f8fafc", titleFont: "Outfit", bodyFont: "Open Sans" },
    sectionDefaults: { bgColor: "transparent", borderStyle: "solid", borderColor: "#dbeafe", borderWidth: 1, rounded: false },
  },
];
